### ISSUE TITLE
Passer en mode mono class

### ISSUE THREAD

**Issue by ghost** [guenneguezt/plugin-ipx800v2#1]

**Comment by ColonelMoutarde** [comment]
Que veux tu dire par là ?

**Comment by ghost** [comment]
Supprimer les classe ipx800v2_analogique, ipx800v2_analogique.... et passer par un type d'équipement.
Je l'ai déjà fait sur les plugins ipx800 et wes. C'est du gros taf, mais c'est nécessaire pour la compatibilité avec le core.
https://github.com/Jeedom-Plugins-Extra/plugin-ipx800v2/tree/master/core/class
